#!/bin/bash
read -p "enter a number:" n
flag=0
for(( i=2; i<n;i++ ))
do
   if((  ((n%i)) == 0 ))
   then
        flag=1
        echo "its not prime no."
     break;
   fi
done

if (( flag != 1))
then
     echo "its prime no."
fi
